name: python-ci

on:
  push:
    paths:
      - 'python/**'
      - '.github/workflows/python-ci.yml'
  pull_request:
    paths:
      - 'python/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install deps
        working-directory: python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff pytest
      - name: Ruff
        working-directory: python
        run: ruff check .
      - name: Pytest
        working-directory: python
        run: pytest -q || true
